
# Site settings
title:  Matheus Francisco 
email: matheusmachadoufsc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Um blog de um estudande de engenharia de computação e apaixonado por desenvolvimento de software e hardware.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://matheusfrancisco.github.io" # the base hostname & protocol for your site
twitter_username: MtChicao
github_username:  matheusfrancisco
linkedin_username: matheus-francisco

#sidebar
default-image: logo-big.jpg  # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: matheusfrancisco
copyright:
   name: matheusfrancisco
   link: ''

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/


# Tracker
analytics: UA-89427393-1

# Comments
disqus-shortname: matheus-francisco

#social
linkedin: linkedin.com/in/matheus-francisco
facebook: https://www.facebook.com/matheusfranciscobatistamachado
#quora: 
twitter: https://twitter.com/@MtChicao
github: http://github.com/matheusfrancisco



# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']